"""C/C++ identifier validation shared across the front-ends.

Generated code uses plugin names, graph names, and node IDs verbatim as C/C++
identifiers (struct names, variables, macros). A name that is a reserved word
passes a plain ``[A-Za-z_][A-Za-z0-9_]*`` check but then fails to compile, so
both the gen~-export and graph front-ends reject reserved words up front.
"""

# C11 keywords + C++ keywords (and alternative operator tokens). A name equal to
# any of these would collide with the language when emitted as an identifier.
C_CPP_RESERVED = frozenset(
    {
        # C keywords
        "auto",
        "break",
        "case",
        "char",
        "const",
        "continue",
        "default",
        "do",
        "double",
        "else",
        "enum",
        "extern",
        "float",
        "for",
        "goto",
        "if",
        "inline",
        "int",
        "long",
        "register",
        "restrict",
        "return",
        "short",
        "signed",
        "sizeof",
        "static",
        "struct",
        "switch",
        "typedef",
        "union",
        "unsigned",
        "void",
        "volatile",
        "while",
        "_Bool",
        "_Complex",
        "_Imaginary",
        # C++ keywords (superset additions)
        "alignas",
        "alignof",
        "and",
        "and_eq",
        "asm",
        "bitand",
        "bitor",
        "bool",
        "catch",
        "char8_t",
        "char16_t",
        "char32_t",
        "class",
        "compl",
        "concept",
        "const_cast",
        "consteval",
        "constexpr",
        "constinit",
        "decltype",
        "delete",
        "dynamic_cast",
        "explicit",
        "export",
        "false",
        "friend",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "not",
        "not_eq",
        "nullptr",
        "operator",
        "or",
        "or_eq",
        "private",
        "protected",
        "public",
        "reinterpret_cast",
        "requires",
        "static_assert",
        "static_cast",
        "template",
        "this",
        "thread_local",
        "throw",
        "true",
        "try",
        "typeid",
        "typename",
        "using",
        "virtual",
        "wchar_t",
        "xor",
        "xor_eq",
    }
)


def is_reserved_word(name: str) -> bool:
    """Return True if ``name`` is a C or C++ reserved word."""
    return name in C_CPP_RESERVED
