"""Tests for the experimental .gdsp -> gen~ (GenExpr) transpiler."""

from __future__ import annotations

import re as _re

import pytest

pytest.importorskip("pydantic")

from gen_dsp.graph.models import (
    Accum,
    AudioInput,
    AudioOutput,
    BinOp,
    Change,
    Clamp,
    Compare,
    Constant,
    Counter,
    Delta,
    Elapsed,
    Fold,
    Graph,
    History,
    Mix,
    NamedConstant,
    Noise,
    Param,
    Pass,
    SampleRate,
    Scale,
    Select,
    Buffer,
    Smoothstep,
    UnaryOp,
    Wrap,
)
from gen_dsp.graph.transpile import (
    NON_DETERMINISTIC_OPS,
    GenExprUnsupportedError,
    genexpr_rename_map,
    transpile_to_genexpr,
)


def _code_only(code: str) -> str:
    """Strip comment lines so identifier assertions ignore the rename notes."""
    return "\n".join(
        line for line in code.splitlines() if not line.lstrip().startswith("//")
    )


def _wrap(nodes, *, inputs=None, outputs=None, params=None, source=None, name="g"):
    """Build a single-output graph around `nodes` for terse tests."""
    if source is None:
        source = nodes[-1].id
    return Graph(
        name=name,
        inputs=inputs or [],
        params=params or [],
        nodes=nodes,
        outputs=outputs or [AudioOutput(id="out1", source=source)],
    )


class TestStructure:
    def test_header_and_io_comment(self) -> None:
        g = _wrap(
            [Constant(id="c", value=1.0)],
            inputs=[AudioInput(id="x")],
            params=[Param(name="p")],
            source="c",
        )
        code = transpile_to_genexpr(g)
        assert code.startswith("// Generated by gen-dsp")
        assert "// Graph: g" in code
        assert "// 1 in, 1 out, 1 param(s)" in code

    def test_output_assignment_uses_positional_name(self) -> None:
        g = Graph(
            name="g",
            nodes=[Constant(id="c", value=0.25)],
            outputs=[AudioOutput(id="anything", source="c")],
        )
        code = transpile_to_genexpr(g)
        assert "out1 = c;" in code

    def test_two_outputs(self) -> None:
        g = Graph(
            name="g",
            nodes=[Constant(id="a", value=1.0), Constant(id="b", value=2.0)],
            outputs=[
                AudioOutput(id="L", source="a"),
                AudioOutput(id="R", source="b"),
            ],
        )
        code = transpile_to_genexpr(g)
        assert "out1 = a;" in code
        assert "out2 = b;" in code

    def test_input_ref_is_positional(self) -> None:
        g = _wrap(
            [BinOp(id="m", op="mul", a="x", b="y")],
            inputs=[AudioInput(id="x"), AudioInput(id="y")],
        )
        code = transpile_to_genexpr(g)
        assert "m = in1 * in2;" in code

    def test_param_default_clamped_to_range(self) -> None:
        g = _wrap(
            [Pass(id="p", a="amp")],
            params=[Param(name="amp", min=0.0, max=1.0, default=5.0)],
        )
        code = transpile_to_genexpr(g)
        assert "Param amp(1.0, min=0.0, max=1.0);" in code


class TestArithmetic:
    def test_binop_operators(self) -> None:
        cases = {
            "add": "r = a + b;",
            "sub": "r = a - b;",
            "mul": "r = a * b;",
            "div": "r = a / b;",
            "mod": "r = a % b;",
            "rsub": "r = b - a;",
        }
        for op, expected in cases.items():
            g = _wrap(
                [
                    Constant(id="a", value=1.0),
                    Constant(id="b", value=2.0),
                    BinOp(id="r", op=op, a="a", b="b"),
                ]
            )
            assert expected in transpile_to_genexpr(g)

    def test_binop_native_functions(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=1.0),
                Constant(id="b", value=2.0),
                BinOp(id="r", op="hypot", a="a", b="b"),
            ]
        )
        assert "r = hypot(a, b);" in transpile_to_genexpr(g)

    def test_binop_pass_through_comparators_are_native(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=1.0),
                Constant(id="b", value=2.0),
                BinOp(id="r", op="gtp", a="a", b="b"),
            ]
        )
        assert "r = gtp(a, b);" in transpile_to_genexpr(g)

    def test_binop_logical(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=1.0),
                Constant(id="b", value=2.0),
                BinOp(id="r", op="and", a="a", b="b"),
            ]
        )
        assert "r = (a != 0 && b != 0);" in transpile_to_genexpr(g)

    def test_unary_direct(self) -> None:
        g = _wrap([Constant(id="a", value=1.0), UnaryOp(id="r", op="sin", a="a")])
        assert "r = sin(a);" in transpile_to_genexpr(g)

    def test_unary_mtof_formula(self) -> None:
        g = _wrap([Constant(id="a", value=69.0), UnaryOp(id="r", op="mtof", a="a")])
        assert "r = 440 * pow(2, (a - 69) / 12);" in transpile_to_genexpr(g)

    def test_unary_neg(self) -> None:
        g = _wrap([Constant(id="a", value=1.0), UnaryOp(id="r", op="neg", a="a")])
        assert "r = -a;" in transpile_to_genexpr(g)

    @pytest.mark.parametrize("op", ["fastsin", "fastcos", "fasttan", "fastexp"])
    def test_unary_fast_ops_unsupported(self, op: str) -> None:
        g = _wrap([Constant(id="a", value=1.0), UnaryOp(id="r", op=op, a="a")])
        with pytest.raises(GenExprUnsupportedError):
            transpile_to_genexpr(g)


class TestRangeAndSelect:
    def test_clamp_wrap_fold_native(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=2.0),
                Clamp(id="c", a="a", lo=0.0, hi=1.0),
                Wrap(id="w", a="a", lo=0.0, hi=1.0),
                Fold(id="f", a="a", lo=0.0, hi=1.0),
            ],
            source="f",
        )
        code = transpile_to_genexpr(g)
        assert "c = clamp(a, 0.0, 1.0);" in code
        assert "w = wrap(a, 0.0, 1.0);" in code
        assert "f = fold(a, 0.0, 1.0);" in code

    def test_scale_native_five_args(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=0.5),
                Scale(id="s", a="a", in_lo=0.0, in_hi=1.0, out_lo=-1.0, out_hi=1.0),
            ],
            source="s",
        )
        assert "s = scale(a, 0.0, 1.0, -1.0, 1.0);" in transpile_to_genexpr(g)

    def test_mix_native(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=0.0),
                Constant(id="b", value=1.0),
                Constant(id="t", value=0.5),
                Mix(id="m", a="a", b="b", t="t"),
            ],
            source="m",
        )
        assert "m = mix(a, b, t);" in transpile_to_genexpr(g)

    def test_select_is_ternary(self) -> None:
        g = _wrap(
            [
                Constant(id="cnd", value=1.0),
                Constant(id="a", value=2.0),
                Constant(id="b", value=3.0),
                Select(id="s", cond="cnd", a="a", b="b"),
            ],
            source="s",
        )
        assert "s = (cnd > 0 ? a : b);" in transpile_to_genexpr(g)

    def test_compare_native(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=1.0),
                Constant(id="b", value=2.0),
                Compare(id="c", op="gte", a="a", b="b"),
            ],
            source="c",
        )
        assert "c = gte(a, b);" in transpile_to_genexpr(g)

    def test_smoothstep_faithful(self) -> None:
        g = _wrap(
            [
                Constant(id="a", value=0.5),
                Smoothstep(id="s", a="a", edge0=0.0, edge1=1.0),
            ],
            source="s",
        )
        code = transpile_to_genexpr(g)
        assert "s_t = clamp((a - 0.0) / (1.0 - 0.0), 0, 1);" in code
        assert "s = s_t * s_t * (3 - 2 * s_t);" in code


class TestNamedConstants:
    def test_native_constant(self) -> None:
        g = _wrap([NamedConstant(id="k", op="pi")])
        assert "k = pi;" in transpile_to_genexpr(g)

    def test_literal_constant(self) -> None:
        g = _wrap([NamedConstant(id="k", op="phi")])
        code = transpile_to_genexpr(g)
        assert "k = 1.618" in code  # phi has no native gen~ operator


class TestStatefulFaithful:
    def test_history_declares_and_writes_back(self) -> None:
        g = _wrap(
            [
                BinOp(id="sum", op="add", a="x", b="fb"),
                History(id="fb", init=0.0, input="sum"),
            ],
            inputs=[AudioInput(id="x")],
            source="sum",
        )
        code = transpile_to_genexpr(g)
        assert "History fb(0.0);" in code
        assert "sum = in1 + fb;" in code
        # The history read needs no compute line; only the store-for-next line.
        assert "fb = sum;" in code

    def test_delta_is_native(self) -> None:
        g = _wrap(
            [Pass(id="x", a="sig"), Delta(id="d", a="x")],
            inputs=[AudioInput(id="sig")],
            source="d",
        )
        assert "d = delta(x);" in transpile_to_genexpr(g)

    def test_change_is_faithful_not_native(self) -> None:
        # gen~ `change` returns sign of difference; ours is a boolean. Must be
        # emitted via History, NOT the native `change` operator.
        g = _wrap([Change(id="c", a="sig")], inputs=[AudioInput(id="sig")], source="c")
        code = transpile_to_genexpr(g)
        assert "History c_prev(0.0);" in code
        assert "c = (in1 != c_prev ? 1 : 0);" in code
        assert "c_prev = in1;" in code
        assert "= change(" not in code

    def test_accum_faithful(self) -> None:
        g = _wrap(
            [Accum(id="a", incr="sig", reset=0.0)],
            inputs=[AudioInput(id="sig")],
            source="a",
        )
        code = transpile_to_genexpr(g)
        assert "History a_sum(0.0);" in code
        assert "a_s = (0.0 > 0 ? 0 : a_sum);" in code
        assert "a_s = a_s + in1;" in code
        assert "a_sum = a_s;" in code

    def test_counter_faithful(self) -> None:
        g = _wrap(
            [Counter(id="cnt", trig="sig", max=4.0)],
            inputs=[AudioInput(id="sig")],
            source="cnt",
        )
        code = transpile_to_genexpr(g)
        assert "History cnt_count(0.0);" in code
        assert "History cnt_ptrig(0.0);" in code
        assert "cnt_inc = (cnt_inc >= trunc(4.0) ? 0 : cnt_inc);" in code

    def test_elapsed_faithful(self) -> None:
        g = _wrap([Elapsed(id="el")])
        code = transpile_to_genexpr(g)
        assert "History el_count(0.0);" in code
        assert "el = el_count;" in code
        assert "el_count = el_count + 1;" in code

    def test_samplerate_native(self) -> None:
        g = _wrap([SampleRate(id="sr")])
        assert "sr = samplerate;" in transpile_to_genexpr(g)


class TestUnsupported:
    @pytest.mark.parametrize(
        "node",
        [
            Buffer(id="b", size=64, fill="sine"),  # codebox cannot init a wavetable
            UnaryOp(id="r", op="fastexp", a="c"),  # bit-trick, not expressible
        ],
    )
    def test_unsupported_nodes_raise(self, node) -> None:
        # Route a constant to the output and include the unsupported node so the
        # graph is otherwise valid.
        g = Graph(
            name="g",
            nodes=[Constant(id="c", value=0.0), node],
            outputs=[AudioOutput(id="out1", source="c")],
        )
        with pytest.raises(GenExprUnsupportedError):
            transpile_to_genexpr(g)


class TestNonDeterministic:
    def test_noise_emits_native_operator(self) -> None:
        g = _wrap([Noise(id="n")])
        code = transpile_to_genexpr(g)
        assert "n = noise();" in code
        assert "out1 = n;" in code

    def test_noise_op_is_marked_non_deterministic(self) -> None:
        assert "noise" in NON_DETERMINISTIC_OPS

    def test_node_named_noise_is_auto_renamed(self) -> None:
        # A node named like the `noise` operator is renamed, not rejected.
        g = _wrap([Constant(id="noise", value=1.0)], source="noise")
        code = transpile_to_genexpr(g)
        assert "noise_ = 1.0;" in code
        assert "out1 = noise_;" in code


class TestIdentifierSafety:
    def test_node_id_colliding_with_operator_is_renamed(self) -> None:
        g = _wrap([Constant(id="mix", value=1.0)], source="mix")
        code = transpile_to_genexpr(g)
        assert "mix_ = 1.0;" in code
        assert "out1 = mix_;" in code
        assert "auto-renamed 'mix' -> 'mix_'" in code

    def test_param_named_like_io_slot_is_renamed(self) -> None:
        g = Graph(
            name="g",
            params=[Param(name="out1")],
            nodes=[Pass(id="p", a="out1")],
            outputs=[AudioOutput(id="o", source="p")],
        )
        code = transpile_to_genexpr(g)
        # The param declaration and every reference use the safe name.
        assert "Param out1_(" in code
        assert "p = out1_;" in code
        assert "out1_" not in code.split("// outputs")[1]  # no stray ref past outputs

    def test_invalid_identifier_still_rejected(self) -> None:
        g = _wrap([Constant(id="has space", value=1.0)], source="has space")
        with pytest.raises(ValueError, match="not a valid identifier"):
            transpile_to_genexpr(g)

    def test_cpp_reserved_word_still_rejected(self) -> None:
        # "double" is a C/C++ reserved word but not a GenExpr operator, so it is a
        # genuine identifier error the renamer does not paper over.
        g = _wrap([Constant(id="double", value=1.0)], source="double")
        with pytest.raises(ValueError, match="C/C\\+\\+ reserved word"):
            transpile_to_genexpr(g)

    def test_output_id_may_look_like_slot(self) -> None:
        # Output ids are remapped positionally, so "out1" as an output id is fine.
        g = Graph(
            name="g",
            nodes=[Constant(id="c", value=1.0)],
            outputs=[AudioOutput(id="out1", source="c")],
        )
        transpile_to_genexpr(g)  # must not raise


class TestAutoRename:
    def test_param_named_mix_is_renamed_consistently(self) -> None:
        # The fbdelay case: a `mix` param crossfaded against `1 - mix`. Every
        # occurrence -- declaration and both references -- must use the safe name,
        # and the gen~ `mix` operator must remain usable elsewhere.
        g = Graph(
            name="fb",
            inputs=[AudioInput(id="input")],
            params=[Param(name="mix", min=0.0, max=1.0, default=0.5)],
            nodes=[
                BinOp(id="inv", op="rsub", a="mix", b=1.0),  # 1 - mix
                BinOp(id="dry", op="mul", a="input", b="inv"),
                BinOp(id="wet", op="mul", a="input", b="mix"),
                BinOp(id="mix_out", op="add", a="dry", b="wet"),
            ],
            outputs=[AudioOutput(id="o", source="mix_out")],
        )
        code = transpile_to_genexpr(g)
        assert "Param mix_(0.5, min=0.0, max=1.0);" in code
        assert "inv = 1.0 - mix_;" in code
        assert "wet = in1 * mix_;" in code
        # No bare `mix` identifier survives in emitted code (it would shadow the
        # operator); the only `mix` left should be inside `mix_` / `mix_out`. The
        # rename-note comment legitimately names the original, so skip comments.
        assert not _re.search(r"\bmix\b", _code_only(code))

    def test_rename_target_avoids_existing_identifier(self) -> None:
        # A param `mix` cannot become `mix_` if a node already owns `mix_`; the
        # renamer must pick the next free name instead.
        g = Graph(
            name="g",
            params=[Param(name="mix", default=0.5)],
            nodes=[
                Pass(id="mix_", a="mix"),
                BinOp(id="o", op="add", a="mix_", b="mix"),
            ],
            outputs=[AudioOutput(id="out", source="o")],
        )
        code = transpile_to_genexpr(g)
        assert "Param mix_2(" in code
        assert "mix_ = mix_2;" in code  # node `mix_` reads the renamed param
        assert "o = mix_ + mix_2;" in code

    def test_node_renamed_buffer_ref_is_rewritten(self) -> None:
        # A node renamed because it collides must also be rewritten where it is
        # referenced by name (e.g. a Buffer id used by BufRead).
        from gen_dsp.graph.models import Buffer, BufRead

        g = Graph(
            name="g",
            nodes=[
                Buffer(id="step", size=8, fill="zeros"),  # `step` is a gen~ op
                BufRead(id="r", buffer="step", index=0.0, interp="none"),
            ],
            outputs=[AudioOutput(id="o", source="r")],
        )
        code = transpile_to_genexpr(g)
        assert "Data step_(8);" in code
        assert "peek(step_," in code
        assert not _re.search(r"\bstep\b", _code_only(code))


class TestRenameMap:
    def test_empty_when_no_collision(self) -> None:
        g = _wrap([Constant(id="c", value=1.0)], source="c")
        assert genexpr_rename_map(g) == {}

    def test_returns_substitutions(self) -> None:
        g = _wrap([Constant(id="mix", value=1.0)], source="mix")
        assert genexpr_rename_map(g) == {"mix": "mix_"}

    def test_map_matches_emitted_comments(self) -> None:
        # The dict must agree with the `auto-renamed` notes in the source so an
        # editor can rely on either.
        g = Graph(
            name="g",
            params=[Param(name="mix", default=0.5)],
            nodes=[Buffer(id="step", size=8, fill="zeros")],
            outputs=[AudioOutput(id="o", source="step")],
        )
        rename = genexpr_rename_map(g)
        code = transpile_to_genexpr(g)
        for orig, new in rename.items():
            assert f"auto-renamed '{orig}' -> '{new}'" in code

    def test_param_order_then_node_order(self) -> None:
        # Insertion order: params first, then nodes, both in declaration order.
        g = Graph(
            name="g",
            params=[Param(name="mix", default=0.5)],
            nodes=[
                Pass(id="mix_", a="mix"),
                BinOp(id="o", op="add", a="mix_", b="mix"),
            ],
            outputs=[AudioOutput(id="out", source="o")],
        )
        rename = genexpr_rename_map(g)
        assert rename == {"mix": "mix_2"}

    def test_consistent_with_transpiler_through_subgraph_expansion(self) -> None:
        # The map is built on the same expanded graph the transpiler emits, so a
        # graph carrying a subgraph still yields a map that agrees with the
        # `auto-renamed` notes in the generated source.
        from gen_dsp.graph.models import Subgraph

        inner = Graph(
            name="inner",
            inputs=[AudioInput(id="x")],
            nodes=[BinOp(id="y", op="mul", a="x", b=2.0)],
            outputs=[AudioOutput(id="o", source="y")],
        )
        g = Graph(
            name="outer",
            inputs=[AudioInput(id="in")],
            params=[Param(name="mix", default=0.5)],
            nodes=[
                Subgraph(id="sub", graph=inner, inputs={"x": "in"}),
                BinOp(id="o", op="mul", a="sub", b="mix"),
            ],
            outputs=[AudioOutput(id="out", source="o")],
        )
        rename = genexpr_rename_map(g)
        assert rename == {"mix": "mix_"}
        code = transpile_to_genexpr(g)
        for orig, new in rename.items():
            assert f"auto-renamed '{orig}' -> '{new}'" in code
