# ssp_toolchain.cmake - cross-compile for the Percussa SSP (Cortex-A17, armhf Linux)
# Generated by gen-dsp. Follows the SSP SDK's xcSSP.cmake: host clang and lld,
# with the Percussa buildroot as sysroot.
#
#   SSP_BUILDROOT  an extracted buildroot (-D or environment). Unset: downloaded
#                  once (608 MB) into the FetchContent cache.
#   TOOLSROOT      directory holding clang and clang++ (environment). Unset:
#                  Homebrew LLVM if present, else PATH.

set(_ssp_name arm-rockchip-linux-gnueabihf_sdk-buildroot)
set(_ssp_url "https://sw13072022.s3.us-west-1.amazonaws.com/${_ssp_name}.tar.gz")

if(NOT SSP_BUILDROOT)
    if(DEFINED ENV{SSP_BUILDROOT})
        set(SSP_BUILDROOT "$ENV{SSP_BUILDROOT}")
    else()
        if(FETCHCONTENT_BASE_DIR)
            set(_ssp_dir "${FETCHCONTENT_BASE_DIR}/ssp-buildroot")
        else()
            set(_ssp_dir "${CMAKE_BINARY_DIR}/_deps/ssp-buildroot")
        endif()
        set(SSP_BUILDROOT "${_ssp_dir}/${_ssp_name}")
        if(NOT EXISTS "${SSP_BUILDROOT}/arm-rockchip-linux-gnueabihf/sysroot")
            message(STATUS "Downloading the SSP buildroot (608 MB) to ${_ssp_dir}")
            file(DOWNLOAD "${_ssp_url}" "${_ssp_dir}/buildroot.tar.gz" SHOW_PROGRESS STATUS _ssp_status)
            list(GET _ssp_status 0 _ssp_code)
            if(NOT _ssp_code EQUAL 0)
                file(REMOVE "${_ssp_dir}/buildroot.tar.gz")
                message(FATAL_ERROR "SSP buildroot download failed: ${_ssp_status}")
            endif()
            # extract to a staging dir so an interrupted run is not mistaken for a complete one
            file(REMOVE_RECURSE "${_ssp_dir}/.part")
            file(ARCHIVE_EXTRACT INPUT "${_ssp_dir}/buildroot.tar.gz" DESTINATION "${_ssp_dir}/.part")
            file(RENAME "${_ssp_dir}/.part/${_ssp_name}" "${SSP_BUILDROOT}")
            file(REMOVE_RECURSE "${_ssp_dir}/.part")
            file(REMOVE "${_ssp_dir}/buildroot.tar.gz")
        endif()
    endif()
    set(SSP_BUILDROOT "${SSP_BUILDROOT}" CACHE PATH "Percussa SSP buildroot" FORCE)
endif()
# try_compile projects re-read this file without the main project's cache
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES SSP_BUILDROOT)

set(_ssp_sysroot "${SSP_BUILDROOT}/arm-rockchip-linux-gnueabihf/sysroot")
if(NOT EXISTS "${_ssp_sysroot}")
    message(FATAL_ERROR "No SSP sysroot at ${_ssp_sysroot}; check SSP_BUILDROOT")
endif()

set(_ssp_hints "$ENV{TOOLSROOT}" /opt/homebrew/opt/llvm/bin /usr/local/opt/llvm/bin)
find_program(SSP_CLANG clang HINTS ${_ssp_hints} NO_CMAKE_FIND_ROOT_PATH REQUIRED)
find_program(SSP_CLANGXX clang++ HINTS ${_ssp_hints} NO_CMAKE_FIND_ROOT_PATH REQUIRED)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(CMAKE_C_COMPILER "${SSP_CLANG}")
set(CMAKE_CXX_COMPILER "${SSP_CLANGXX}")
set(CMAKE_C_COMPILER_TARGET arm-linux-gnueabihf)
set(CMAKE_CXX_COMPILER_TARGET arm-linux-gnueabihf)
set(CMAKE_SYSROOT "${_ssp_sysroot}")

# clang does not find the buildroot's GCC 8.4 libstdc++ by itself: its triple differs
set(_ssp_gcc "${SSP_BUILDROOT}/lib/gcc/arm-rockchip-linux-gnueabihf/8.4.0")
set(_ssp_cxx "${SSP_BUILDROOT}/arm-rockchip-linux-gnueabihf/include/c++/8.4.0")
set(_ssp_cpu "-mcpu=cortex-a17 -mfloat-abi=hard -mfpu=neon-vfpv4")
set(CMAKE_C_FLAGS_INIT "${_ssp_cpu}")
set(CMAKE_CXX_FLAGS_INIT "${_ssp_cpu} -isystem ${_ssp_cxx} -isystem ${_ssp_cxx}/arm-rockchip-linux-gnueabihf")

set(_ssp_link "-fuse-ld=lld -L${_ssp_sysroot}/lib -B${_ssp_sysroot}/lib -Wl,-rpath-link,${_ssp_sysroot}/lib")
set(_ssp_link "${_ssp_link} -L${_ssp_gcc} -B${_ssp_gcc} -Wl,-rpath-link,${_ssp_gcc}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_ssp_link}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_ssp_link}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_ssp_link}")

# pkg-config (JUCE's FreeType lookup) must search the sysroot. The settings go inside
# ENV{PKG_CONFIG}, which JUCE unsets for its host juceaide build.
set(ENV{PKG_CONFIG} "${CMAKE_COMMAND} -E env --unset=PKG_CONFIG_PATH PKG_CONFIG_LIBDIR=${_ssp_sysroot}/usr/lib/pkgconfig:${_ssp_sysroot}/usr/share/pkgconfig PKG_CONFIG_SYSROOT_DIR=${_ssp_sysroot} pkg-config")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
