#-----------------------------------
# makefile.linux
# Linux-specific build configuration
#-----------------------------------

# compiler flags
FLAGS+=-D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -I$(CK_SRC_PATH) -fPIC
# linker flags
LDFLAGS+=-shared

# which C++ compiler to use
CXX=g++
# which linker to use
LD=gcc
